-- Email templates for order lifecycle events. Used by senders wired in
-- event-consumer.js: subscribe to order.paid/shipped/delivered/cancelled/
-- refunded and produce one email per transition.
INSERT INTO platform_notifications.templates (key, channel, locale, subject, body_text, variables) VALUES
  ('order.paid', 'email', 'es',
   'Pago confirmado · Pedido #{{orderId}}',
   'Hola,' || E'\n\n' || 'Hemos recibido el pago de tu pedido #{{orderId}} ({{total}}). Te avisaremos cuando se envíe.',
   ARRAY['orderId', 'total']),
  ('order.paid', 'email', 'en',
   'Payment received · Order #{{orderId}}',
   'Hi,' || E'\n\n' || 'We have received the payment for your order #{{orderId}} ({{total}}). We will notify you when it ships.',
   ARRAY['orderId', 'total']),
  ('order.shipped', 'email', 'es',
   'Tu pedido va en camino · #{{orderId}}',
   'Hola,' || E'\n\n' || 'Tu pedido #{{orderId}} ya está en camino.{{trackingLine}}',
   ARRAY['orderId', 'trackingLine']),
  ('order.shipped', 'email', 'en',
   'Your order is on its way · #{{orderId}}',
   'Hi,' || E'\n\n' || 'Your order #{{orderId}} is on its way.{{trackingLine}}',
   ARRAY['orderId', 'trackingLine']),
  ('order.delivered', 'email', 'es',
   'Pedido entregado · #{{orderId}}',
   'Hola,' || E'\n\n' || 'Tu pedido #{{orderId}} ha sido entregado. Esperamos que disfrutes de tu compra.',
   ARRAY['orderId']),
  ('order.delivered', 'email', 'en',
   'Order delivered · #{{orderId}}',
   'Hi,' || E'\n\n' || 'Your order #{{orderId}} has been delivered. We hope you enjoy it.',
   ARRAY['orderId']),
  ('order.cancelled', 'email', 'es',
   'Pedido cancelado · #{{orderId}}',
   'Hola,' || E'\n\n' || 'Tu pedido #{{orderId}} ha sido cancelado.{{reasonLine}} Si esto no es lo que esperabas, contacta con soporte.',
   ARRAY['orderId', 'reasonLine']),
  ('order.cancelled', 'email', 'en',
   'Order cancelled · #{{orderId}}',
   'Hi,' || E'\n\n' || 'Your order #{{orderId}} has been cancelled.{{reasonLine}} If this is not what you expected, please contact support.',
   ARRAY['orderId', 'reasonLine']),
  ('order.refunded', 'email', 'es',
   'Reembolso emitido · #{{orderId}}',
   'Hola,' || E'\n\n' || 'Hemos emitido el reembolso de tu pedido #{{orderId}} ({{total}}). Puede tardar varios días en reflejarse en tu cuenta.',
   ARRAY['orderId', 'total']),
  ('order.refunded', 'email', 'en',
   'Refund issued · #{{orderId}}',
   'Hi,' || E'\n\n' || 'We have issued a refund for your order #{{orderId}} ({{total}}). It can take several days to appear on your statement.',
   ARRAY['orderId', 'total'])
ON CONFLICT (key, channel, locale) DO NOTHING;
