process.env.DATABASE_URL           ??= 'postgresql://splitpay:splitpay@localhost:5432/splitpay'
process.env.REDIS_URL              ??= 'redis://localhost:6379'
process.env.SENDGRID_API_KEY        = 'dev_no_sendgrid'
process.env.SENDGRID_FROM_EMAIL     = 'noreply@test.local'
process.env.EXPECTED_APP_ID         = 'platform'
process.env.NODE_ENV                = 'test'
process.env.LOG_LEVEL               = 'error'
