process.env.DATABASE_URL           ??= 'postgresql://splitpay:splitpay@localhost:5432/splitpay'
process.env.REDIS_URL              ??= 'redis://localhost:6379'
process.env.RESEND_API_KEY        = ''
process.env.EMAIL_FROM_ADDRESS    = 'noreply@test.local'
process.env.EXPECTED_APP_ID         = 'platform'
process.env.NODE_ENV                = 'test'
process.env.LOG_LEVEL               = 'error'
