process.env.DATABASE_URL            ??= 'postgresql://svc_platform_bookings:platform_bookings_secret@localhost:5432/splitpay'
process.env.MIGRATION_DATABASE_URL  ??= 'postgresql://splitpay:splitpay@localhost:5432/splitpay'
process.env.REDIS_URL               ??= 'redis://localhost:6379'
process.env.EXPECTED_APP_ID          = 'platform'
process.env.NODE_ENV                 = 'test'
process.env.LOG_LEVEL                = 'error'
